### ISSUE TITLE
Sometimes you cant start connection until restart

### ISSUE THREAD

**Issue by majkinetor** [1Remote/PRemoteM#213] opened 2022-02-28 20:55 UTC
It happened 3 times since yesterday that I can't start a connection, it just does nothing in both launcher and the list. After the restart, it works.

**Comment by VShawn** [comment] 2022-03-02 01:37
close by https://github.com/VShawn/PRemoteM/commit/6fa1fcb49a0b0e5fb9d5e3c07d8d7ab710a6ade8

**Comment by majkinetor** [comment] 2022-04-02 17:14
Still happens with 0.6.2.1. Not sure when it happens, I know it happened each time when I was doing some config editing and/or duplicating. I am having trouble reproducing it, but once it happens you need to restart PRM.

**Comment by majkinetor** [comment] 2022-04-18 19:42
I am having hard time troubleshooting this. When it happens, and I delete logs before trying connection, this is the only thing that shows:

```
2022-04-18T21:40:51.5272722+02:00[ThreadId:0000000001]		Debug		Call shortcut to invoke launcher _isHidden = True
2022-04-18T21:40:51.5322590+02:00[ThreadId:0000000001]		Debug		Launcher resize:  w = 400, h = 366
2022-04-18T21:40:52.0180296+02:00[ThreadId:0000000001]		Debug		Call HideMe()
2022-04-18T21:40:52.0200281+02:00[ThreadId:0000000001]		Debug		Call HideMe()
2022-04-18T21:40:52.0210280+02:00[ThreadId:0000000001]		Debug		SetSelfStartingHelper.SetSelfStartByRegistryKey(True, "PRemoteM")
2022-04-18T21:40:52.3225347+02:00[ThreadId:0000000001]		Debug		Launcher resize:  w = 400, h = 366
```

Anything I can do to identify the reason besides turning development environment up? Perhaps you can enrich logs regarding this?

**Comment by VShawn** [comment] 2022-04-19 00:42
sorry I didn't notice the reopened ticket.

I dont know why it never happen to me.

But when next time it happens, you can 

![image](https://user-images.githubusercontent.com/10143738/163897929-a574c766-24b3-4f86-a120-9d98e1d6514a.png)

And you will get a consol window.

Then try start a connection with nothing happen, PRM will print log on the consol, just show me the log : )

**Comment by VShawn** [comment] 2022-04-19 08:42
> It does seem to have something to do with reconnecting after idle period. When I restart the app and try connecting to local server, I get immediately reconnect screen which is strange, since I just restarted PRM:

Based on the information you gave, maybe there some error during the initialization, it sotp the connection initialization( and the remote window init) but not be thrown. 

Then the un-init RDP connection will be remembered by the RemoteWindowPool and your next connecte command will be rejected by:

https://github.com/VShawn/PRemoteM/blob/dev/PRemoteM/Model/RemoteWindowPool.cs#L304-L306


That's my reasoning

**Comment by majkinetor** [comment] 2022-04-19 11:31
Regarding Support clicking window, it looks like this console provides the same logs as those in the .md logs ?

**Comment by majkinetor** [comment] 2022-04-23 21:08
I found out that just one connection cant be started. Others worked. After the restart, it resolved.

![prm](https://user-images.githubusercontent.com/85767/164946020-220a80a1-3de1-41e4-9c4f-3f166297d9c8.gif)

**Comment by VShawn** [comment] 2022-04-24 01:27
I‘ve made a SessionControlService.cs instead of RemoteWindowPool.cs yesterday, I think it would fix this.

https://github.com/VShawn/PRemoteM/blob/dev_net6/Ui/Service/SessionControlService.cs

**Comment by VShawn** [comment] 2022-07-14 00:35
> After Installation of 0.7.0 it's More worse then before. Only a restart of the Software helps. 😔

That's awful. 

Worse, I couldn't reproduce the problem so that I can't locate how the bug cause.

===


@majkinetor Do you still have this problem?

**Comment by stetze88** [comment] 2022-07-14 03:29
My workmate have the Same Problems. We Both use Windows 11 pro and the Store Version.

**Comment by VShawn** [comment] 2022-07-14 06:13
> My workmate have the Same Problems. We Both use Windows 11 pro and the Store Version.

I don't have a win11 installed on my pc, so PRemoteM are not been fully tested on Win11. Only the portable exe been tested on a virtual machine win11.

You can sharing me the log when you meet the bug, may be we can find something in the logs.

**Comment by majkinetor** [comment] 2022-07-14 07:32
I think I still have it but its rare. Using w10.

**Comment by stetze88** [comment] 2022-07-14 14:05
With the github zip Version 0.6.2 it's much better. I Try tomorrow the 0.7 zip Version. Maybe it Makes an Difference against the Store Version.

**Comment by ndd200** [comment] 2022-07-18 03:10
我有同样的问题。
于是我装了Github版便携模式，商店版配置存appdata。两个版本用同一个PRemoteM.db。对比两边的json配置，几乎是一样的，但是商店版打开某几个远程就是看着像连上了，在调整分辨率的时候闪退了，重启程序也无法解决。
本来还想仔细研究的，在反复重启的过程中，两个版本又都不闪退了。

———————割一下———————
现在大致可以确认，有问题的是商店版。
商店版连接某几台服务器时候，会闪一下退出连接。同一时间，关商店版，启动Git版没问题。然后再关Git版，启动商店版就闪退。
两个版本的Locality.json和PRemoteM.json配置是一致的，尤其是分辨率完全一样。

日志里错误都是error code 4360。


[T:001][10:59:57.069]	`Debug`		RDP Host: RdpOnDisconnected
[T:001][10:59:57.070]	`Debug`		AxMsRdpClient09Host: Status => Disconnected
[T:001][10:59:57.071]	`Warning`		[AxMsRdpClient09Host.cs(OnRdpClientDisconnected:102)]	RDP(blablabla) exit with error code 4360(未能重新连接到远程会话。
请重新尝试连接。)
[T:001][10:59:57.554]	`Debug`		RDP Host: _rdpClient.Dispose()
[T:019][10:59:57.558]	`Debug`		MarkProtocolHostToClose: marking to close: AxMsRdpClient09Host(id = 40, hash = 13273752)
[T:019][10:59:57.559]	`Debug`		Current: Host = 0, Full = 0, Tab = 1, HostToBeDispose = 1
[T:019][10:59:57.562]	`Debug`		CloseEmptyWindows: closing tab(16355056)
[T:019][10:59:57.563]	`Info`		CloseEmptyWindows: Current: Host = 0, Full = 0, Tab = 0, HostToBeDispose = 1, WindowToBeDispose = 1
[T:019][10:59:57.563]	`Warning`		[SessionControlService.cs(<CloseProtocolHostAsync>b__0:535)]	CloseEmptyWindows: 1 Empty Host closed
[T:019][10:59:57.565]	`Debug`		Closing: 1 Empty Host.
[T:019][10:59:57.566]	`Info`		CloseMarkedProtocolHost: Current: Host = 0, Full = 0, Tab = 0, HostToBeDispose = 0
[T:001][10:59:57.595]	`Debug`		RDP Host: _rdpClient.Dispose()

**Comment by meyomey** [comment] 2022-07-20 07:42
Hi VShawn, with the Store version (0.7.0) I can currently only create one connection. No improvement even after a restart. With the Github version everything is ok.

**Comment by VShawn** [comment] 2022-07-21 06:09
> Hi VShawn, with the Store version (0.7.0) I can currently only create one connection. No improvement even after a restart. With the Github version everything is ok. (both runs under win10)

@meyomey Can you provide the running log of store version after reproduct the bug? I can figure out what's happening with the log.

**Comment by meyomey** [comment] 2022-07-21 06:52
How do I start the console? Right-click three times on Support unfortunately doesn't work.

**Comment by chrisonline** [comment] 2022-07-21 13:49
Same problem here on Windows 11 and Store version.
I can connect to one server. If I want to connect to a second server, it opens and closes immediately.

**Comment by VShawn** [comment] 2022-07-22 06:58
found a same ticket here: https://forum.asg-rd.com/showthread.php?tid=11016

As this guy said

```
I'm sorry to hear that. Right now it's not clear what could cause those issues only on some installations. 
As my colleague stated we didn't change anything related to RDP in patch3. 
So first we need time to be able to reproduce the problem on our side and 
also this month is affected by vacation so things generally need a bit 
more time. If you extended your license then you will be able use the next patches as well.
```

I didn't change anything related to RDP in 0.7.0.

**Comment by chrisonline** [comment] 2022-07-22 07:39
Hi @VShawn !

Attached is the log file with the error message:
System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.

What I did:
Open RDP Session to Server 1 and the session is still running
Now try to open RDP Session to Server 2 and it seems it is connection. I see very short the blue RDP tab and it closes afterwards.

[PRemoteM.log_20220722.md](https://github.com/1Remote/PRemoteM/files/9165692/PRemoteM.log_20220722.md)
.

**Comment by majkinetor** [comment] 2022-07-22 07:59
It looks like we have 2 similar problems here. In my original report on selection nothing happens at all.

**Comment by VShawn** [comment] 2022-07-22 08:00
@chrisonline 

Hi thanks for your log. Accroding to the log the error was:

```
[T:001][09:34:59.509]	`Warning`		[AxMsRdpClient09Host.cs(OnRdpClientDisconnected:103)]	RDP(Interalp 2 (SalesBox + WebBox)) exit with error code 4360(Das Wiederherstellen der Verbindung mit der Remotesitzung ist fehlgeschlagen.
Wiederholen Sie den Verbindungsversuch.)

```

**Comment by VShawn** [comment] 2022-07-22 08:07
> It looks like we have 2 similar problems here. In my original report on selection nothing happens at all.

You are right. One is because of the mess control logic in the `SessionControlService` (the original one you report). In this case, the session will not be opened.

The other one is happen in the store version which I can't not locate where the bug is.(RDP exit with error code 4360.) In this case, the session opens and closes immediately.

**Comment by stetze88** [comment] 2022-07-22 10:26
> @chrisonline 
> 
> 
> 
> Hi thanks for your log. Accroding to the log the error was:
> 
> 
> 
> ```
> 
> [T:001][09:34:59.509]	`Warning`		[AxMsRdpClient09Host.cs(OnRdpClientDisconnected:103)]	RDP(XXXXX) exit with error code 4360(Das Wiederherstellen der Verbindung mit der Remotesitzung ist fehlgeschlagen.
> 
> Wiederholen Sie den Verbindungsversuch.)
> 
> 
> 
> ```
> 
>  

I have the Same error on my Store Version 0.7.0 with Windows 11 Pro (German).

**Comment by chrisonline** [comment] 2022-07-22 11:07
FYI

I use also the latest Store Version on Windows 11 (German).

**Comment by meyomey** [comment] 2022-07-22 12:10
as an addition from me (Store Version):
> [T:001][13:56:39.244]	`Warning`		[AxMsRdpClient09Host.cs(OnRdpClientDisconnected:103)]	RDP(73 - MBT-73) exit with error code 4360(Das Wiederherstellen der Verbindung mit der Remotesitzung ist fehlgeschlagen.
Wiederholen Sie den Verbindungsversuch.)

**Comment by VShawn** [comment] 2022-07-23 03:22
0.7.1.1 is in publish processing, and this patch may fix `rdp error code 4360`

![image](https://user-images.githubusercontent.com/10143738/180588603-256f92f4-27da-4b3e-9ff5-78907a5dec24.png)

tested in my store beta test group, no more 4360 reproduce

![image](https://user-images.githubusercontent.com/10143738/180588714-25608548-096c-47f8-8384-6fbee497bbca.png)



Please help me test this build, it will be published after a certification(up to 3 business days).

![image](https://user-images.githubusercontent.com/10143738/180588676-6e7b10c7-afeb-4124-ab41-8b1b1110a2ab.png)

**Comment by stetze88** [comment] 2022-07-24 08:34
> 0.7.1.1 is in publish processing, and this patch may fix `rdp error code 4360`
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/10143738/180588603-256f92f4-27da-4b3e-9ff5-78907a5dec24.png)
> 
> 
> 
> tested in my store beta test group, no more 4360 reproduce
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/10143738/180588714-25608548-096c-47f8-8384-6fbee497bbca.png)
> 
> 
> 
> 
> 
> 
> 
> Please help me test this build, it will be published after a certification(up to 3 business days).
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/10143738/180588676-6e7b10c7-afeb-4124-ab41-8b1b1110a2ab.png)
> 
> 

I think it's fixed. More Tests tomorrow at work.

**Comment by VShawn** [comment] 2022-07-25 00:21
@stetze88  sorry but the fix patch(0.7.1.1) has not been certificated yet, it still in the certification queue of Microsoft store.

**Comment by VShawn** [comment] 2022-07-26 03:44
hey guys, 0.7.1.1 is available in the store now :)

**Comment by meyomey** [comment] 2022-07-26 05:19
Hi vshawn,
just tested the new store version at work. Works fine again. Thanks a lot!
And of course for your quick response.

**Comment by stetze88** [comment] 2022-07-26 13:38
It's much better. But the Problem still Exists after a Long time of using.

**Comment by VShawn** [comment] 2022-07-27 00:18
> It's much better. But the Problem still Exists after a Long time of using.

desponding. can you check the log? is it still rdp error code 4360?

**Comment by meyomey** [comment] 2022-07-27 08:26
Hi VShawn, in my case the connection was interrupted after half an hour and the programme was partially blocked. Unfortunately, error 4360 appears again in the log file....

[PRemoteM.log_20220727.md](https://github.com/1Remote/PRemoteM/files/9196462/PRemoteM.log_20220727.md)

**Comment by VShawn** [comment] 2022-07-28 00:31
> Hi VShawn, today the connection was interrupted after half an hour and the programme was partially blocked. Unfortunately, error 4360 appears again in the log file....

Damn this bug :(

Maybe I should revert and leave store version at 0.6.X. 

Anyway thanks for your testing.

**Comment by chrisonline** [comment] 2022-07-28 08:05
For me, it is working fine so far. :-)
Thanks!

**Comment by VShawn** [comment] 2022-09-14 02:50
by #263 and this ticket,  seems it is working now.

**Closed by VShawn** 2022-09-14 02:50 UTC
Labels: bug
